# Generated by Django 5.1.1 on 2024-10-14 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+71234567890'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
