# Generated by Django 5.1.1 on 2024-10-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название услуги')),
                ('description', models.TextField(verbose_name='описание услуги')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='стоимость услуги')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_services', to='index.room')),
            ],
            options={
                'verbose_name': 'дополнительная услуга',
                'verbose_name_plural': 'дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='детали комнаты')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='площадь комнаты')),
                ('balcony', models.BooleanField(default=False, verbose_name='балкон')),
                ('air_conditioning', models.BooleanField(default=False, verbose_name='кондиционер')),
                ('microwave', models.BooleanField(default=False, verbose_name='микроволновая печь')),
                ('minikitchen', models.BooleanField(default=False, verbose_name='кухня')),
                ('refrigerator', models.BooleanField(default=False, verbose_name='холодильник')),
                ('tv', models.BooleanField(default=False, verbose_name='телевизор')),
                ('kettle', models.BooleanField(default=False, verbose_name='чайник')),
                ('bathrooms', models.IntegerField(default=1, verbose_name='душевая')),
                ('wifi', models.BooleanField(default=False, verbose_name='wi-fi')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='index.room')),
            ],
            options={
                'verbose_name': 'детали номера',
                'verbose_name_plural': 'детали номера',
            },
        ),
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование особенности')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование особенности')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='index.room')),
            ],
            options={
                'verbose_name': 'особенность номера',
                'verbose_name_plural': 'особенности номера',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='фото комнаты')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='название фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='index.room')),
            ],
            options={
                'verbose_name': 'фото номера',
                'verbose_name_plural': 'фото номера',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField(verbose_name='описание правил')),
                ('rule_number', models.IntegerField(verbose_name='порядковый номер правила')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='index.room')),
            ],
            options={
                'verbose_name': 'правило отеля',
                'verbose_name_plural': 'правила отеля',
            },
        ),
    ]
