# Generated by Django 5.1.1 on 2024-10-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'бронирование', 'verbose_name_plural': 'бронирования'},
        ),
        migrations.AlterModelOptions(
            name='bookingsettings',
            options={'verbose_name': 'настройка бронирования', 'verbose_name_plural': 'настройки бронирования'},
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='period_of_each_booking',
            field=models.CharField(choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default='60', help_text='How long each booking take.', max_length=3),
        ),
    ]
