# Generated by Django 5.1.1 on 2024-10-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_options_alter_bookingsettings_options_and_more'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='available_booking_months',
            field=models.IntegerField(default=1, help_text='если 2, пользователь может забронировать номер только на следующие два месяца.'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='max_booking_per_time',
            field=models.IntegerField(default=1, help_text='сколько номеров можно забронировать за каждый раз.'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='period_of_each_booking',
            field=models.CharField(choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default='60', help_text='сколько времени занимает бронирование.', max_length=3),
        ),
    ]
