# Generated by Django 5.1.1 on 2024-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_room_alter_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_check_out',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
