# Generated by Django 5.1.1 on 2024-10-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название комнаты')),
                ('description', models.TextField(verbose_name='описание комнаты')),
                ('price', models.PositiveIntegerField(verbose_name='стоимость за сутки')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='фото комнаты')),
                ('hourly', models.BooleanField(default=False, verbose_name='почасовая аренда')),
            ],
            options={
                'verbose_name': 'номер',
                'verbose_name_plural': 'номера',
            },
        ),
    ]
